[tool.poetry]
name = "modelo-knn-iris"
version = "0.1.0"
description = "Aplicacion Streamlit para clasificacion de clusters K-Means mediante K-NN"
authors = ["Mateo"]

package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
streamlit = "1.50.0"
pandas = "2.3.3"
numpy = "2.3.4"
scikit-learn = "1.7.2"
joblib = "1.5.2"
